[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
cmds = ["pip3 install -r requirements.txt"]

[phases.build]
cmds = ["python3 manage.py collectstatic --noinput --clear"]

[start]
cmd = "python railway_start.py"
